Update Trigger in sequence.yml
Signed-off-by: REIJI007 <miyajimareji007@gmail.com>

diff --git a/.github/workflows/Trigger in sequence.yml b/.github/workflows/Trigger in sequence.yml
--- a/.github/workflows/Trigger in sequence.yml
+++ b/.github/workflows/Trigger in sequence.yml
@@ -174,23 +174,23 @@ jobs:
           # 等待90秒
           sleep 90
 
-  trigger_release_adblock_file:
+  trigger_generate_matcher_ruleset_entries_surge:
     runs-on: ubuntu-latest
-    needs: trigger_adblock_rule_generator_txt
+    needs: trigger_generate_matcher_ruleset_entries_clash
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3  # 检出仓库代码
 
-      - name: Trigger and verify Release_ADblock_file
+      - name: Trigger and verify Generate_Matcher_Ruleset_entries_SURGE
         env:
           TOKEN: ${{ secrets.TOKEN }}
         run: |
-          workflow_id="Release_ADblock_file.yml"
+          workflow_id="Generate_Matcher_Ruleset_entries_SURGE.yml"
           ref="main"
           # 触发工作流
           response=$(curl -X POST -H "Authorization: token $TOKEN" \
             -H "Accept: application/vnd.github.v3+json" \
-            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Surge/actions/workflows/$workflow_id/dispatches" \
+            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/workflows/$workflow_id/dispatches" \
             -d "{\"ref\":\"$ref\"}")
           echo "Triggered workflow $workflow_id: $response"
 
@@ -198,17 +198,65 @@ jobs:
           while : ; do
             status=$(curl -s -H "Authorization: token $TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
-              "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Surge/actions/runs?workflow_id=$workflow_id&status=in_progress&branch=$ref" \
-              | jq -r '.workflow_runs[0].status')
+              "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/runs?workflow_id=$workflow_id&status=completed&branch=$ref" \
+              | jq -r '.workflow_runs[0].conclusion')
 
-            if [[ "$status" == "in_progress" ]]; then
-              echo "Workflow $workflow_id is running."
+            if [[ "$status" == "success" ]]; then
+              echo "Workflow $workflow_id completed successfully."
               break
+            elif [[ "$status" == "failure" ]]; then
+              echo "Workflow $workflow_id failed."
+              exit 1
             else
-              echo "Waiting for workflow $workflow_id to start..."
+              echo "Waiting for workflow $workflow_id to complete..."
               sleep 30
             fi
           done
+
+          # 等待90秒
+          sleep 90
+
+  trigger_release_adblock_file:
+    runs-on: ubuntu-latest
+    needs: trigger_generate_matcher_ruleset_entries_surge
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3  # 检出仓库代码
+
+      - name: Trigger and verify Release_Adblock_file
+        env:
+          TOKEN: ${{ secrets.TOKEN }}
+        run: |
+          workflow_id="Release_Adblock_file.yml"
+          ref="main"
+          # 触发工作流
+          response=$(curl -X POST -H "Authorization: token $TOKEN" \
+            -H "Accept: application/vnd.github.v3+json" \
+            "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/workflows/$workflow_id/dispatches" \
+            -d "{\"ref\":\"$ref\"}")
+          echo "Triggered workflow $workflow_id: $response"
+
+          # 验证工作流成功触发
+          while : ; do
+            status=$(curl -s -H "Authorization: token $TOKEN" \
+              -H "Accept: application/vnd.github.v3+json" \
+              "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Clash/actions/runs?workflow_id=$workflow_id&status=completed&branch=$ref" \
+              | jq -r '.workflow_runs[0].conclusion')
+
+            if [[ "$status" == "success" ]]; then
+              echo "Workflow $workflow_id completed successfully."
+              break
+            elif [[ "$status" == "failure" ]]; then
+              echo "Workflow $workflow_id failed."
+              exit 1
+            else
+              echo "Waiting for workflow $workflow_id to complete..."
+              sleep 30
+            fi
+          done
+
+          # 等待90秒
+          sleep 90
 
   check_all_workflows:
     runs-on: ubuntu-latest
